config/routes.rb
Doless::Application.routes.draw do
  
  get "profile/:id", :as=>'profile', :to=>'profile#show'

  resources :updates

  resources :tasks do
    member do
      get 'switch_completed'
      get 'switch_starred'
    end
    collection do
      get 'starred'
      get 'completed'
    end
  end

  scope ':project_id', :as=>'project' do
    resources :documents
    
    resources :tasks do
      member do
        get 'switch_completed'
      end
    end
    
    resources :tickets do
      resources :ticket_comments, :only=>[:index, :create, :destroy]
    end
    resources :topics do
      resources :posts, :only=>[:index, :create, :destroy]
    end
    resources :work_reports
  end
  resources :projects do
    collection do
      get 'all'
    end
  end
  
  resource :dashboard

  devise_for :users

  root :to => "dashboards#show"

  match ':id' => "projects#show", :as=>:short_project
end

app/models/task.rb
class Task < ActiveRecord::Base
  
  scope :active, where('is_completed=?', false).order('is_starred DESC')
  scope :completed, where('is_completed=?', true).order('updated_at DESC')
  scope :starred, where('is_starred=?', true)
  
  belongs_to :project
  belongs_to :user
  
  validates :title, :presence=>true
  attr_accessible :title, :is_starred
  
  
  def to_s
    self.title
  end
  
  def switch_completed
    self.is_completed = !self.is_completed
  end
  
  def switch_completed!
    switch_completed
    save
  end
  
  def switch_starred
    self.is_starred = !self.is_starred
  end
  
  def switch_starred!
    switch_starred
    save
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :try_to_find_project
  before_filter :generate_new_task, :only=>[:index, :starred, :completed]
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = context.active.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
      format.json { render :json => @tasks }
      format.js { render 'list' }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = context.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
      format.js { render :json=>@task}
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = context.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = context.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = context.new(params[:task])
    @task.project = @project
    @task.user = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to(redirect, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
        format.js { render :json=>@task}
        
      else
        format.html { redirect_to(redirect, :notice => 'Please try again.') }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
        format.js { render :json=>@task.errors, :status => :unprocessable_entity}
        
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = context.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(redirect, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { redirect_to(redirect, :notice => 'Please try again') }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = context.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
  
  def switch_completed
    @task = context.find(params[:id])
    @task.switch_completed!
    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.js { render :json=>@task }
    end
  end
  
  def switch_starred
    @task = context.find(params[:id])
    @task.switch_starred!
    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.js { render :json=>@task }
    end
  end
  
  def starred
    @tasks = context.active.starred
    respond_to do |format|
      format.html { render :action=>"index" }
      format.json { render :json=>@tasks }
      format.js { render 'list' }
    end
  end
  
  def completed
    @tasks = context.completed
    respond_to do |format|
      format.html { render :action=>"index" }
      format.json { render :json=>@tasks }
      format.js { render 'list' }
    end
  end
  
  private
    
    def context
      @project.blank? ? current_user.tasks : current_user.tasks.where('project_id=?', @project.id)
    end
    
    def redirect
      tasks_url(:project_id=>@project.to_param)
    end
    
    def try_to_find_project
      begin
        find_project
      rescue
        @project = nil
      end
    end
    
    def generate_new_task
      @task = Task.new
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for [@task], :url=>tasks_path(:project_id=>@project.to_param), :html => { :class => :form } do |f| -%>

  <div class="group">
    <%= f.label :title, t("activerecord.attributes.task.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description"><% t("web-app-theme.descriptions.task.title", :default => "") %></span>
  </div>
        
  <div class="group navform wat-cf">
    <button class="button" type="submit">
      <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
    </button>
    <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
    <%= link_to t("web-app-theme.cancel", :default => "Cancel"), tasks_path, :class => "text_button_padding link_button" %>
  </div>
<% end -%>

app/views/tasks/_index_sidebar.html.erb
<div class="block notice">
  <h3>Tasks</h3>
  <ul class="navigation">
    <li class="task_list"><%= link_to "All", tasks_path(:project_id=>@project), :'js-href'=>tasks_path(:project_id=>@project, :format=>:js), :id=>"list_all_href" %></li>
    <li class="task_list"><%= link_to "Starred", starred_tasks_path(:project_id=>@project), :'js-href'=>starred_tasks_path(:project_id=>@project, :format=>:js), :id=>"list_starred_href" %></li>
    <li class="task_list"><%= link_to "Completed", completed_tasks_path(:project_id=>@project), :'js-href'=>completed_tasks_path(:project_id=>@project, :format=>:js), :id=>"list_completed_href" %></li>
  </ul>
</div>

<div class="block notice">
  <h3>By project</h3>
  <ul class="navigation">
    <li><a href="#">...</a></li>
  </ul>
</div>

app/views/tasks/_list.erb
<% @tasks.each do |task| -%>
<%= render :partial=>task%>
<% end -%>

app/views/tasks/_task.html.erb
<li class="single_task_wrapper" id="task_id_<%= task.id %>">
  <div class="checkbox_left">
    <%= check_box_tag :id, task.id, task.is_completed %>
  </div>
  <div class="task_title">
    <% if @project.blank? and not task.project.blank? %> 
      <span class="project_context"><%= "[#{task.project.name}]" %></span>
    <% end %>  
    <%= task.title %>
  </div>
</li>

app/views/tasks/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", tasks_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_task_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_task_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Task</h2>
    <div class="inner">
      <%= render :partial => "form"%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/tasks/index.html.erb
<%= content_for :head do %>
<script type="text/javascript" charset="utf-8">
  var form_url = '<%= tasks_path(:project_id=>@project.to_param) %>';
  var completed_url = '<%= switch_completed_task_path(-1, :project_id=>@project.to_param) %>';
  var starred_url = '<%= switch_starred_task_path(-1, :project_id=>@project.to_param) %>';
  
  function add_new_task(resp, status, xhr, form)
  {
    if(status=='success'){
      var elem = $(single_task).appendTo('ul#task_items').fadeIn();
      $(elem).children('.task_title').text(resp.task.title);
    }
  };
  function switch_task_status()
  {
    var id = $(this).attr('value');
    var replace_url = completed_url.replace(/\-1/, id);
    jQuery.getJSON(replace_url, function(data, test_status){
      $('#task_id_'+id).fadeOut();
    });
  }
  
  function star_task()
  {
    var id = $(this).attr('data-value');
    var replace_url = starred_url.replace(/\-1/, id);
    jQuery.getJSON(replace_url, function(data, text_status){
      $('#task_id_'+id).fadeOut();
    });
    
  }
  
  var single_task = "<%= escape_javascript(render(:partial=>@task)) %>";
  $(document).ready(function(){
    $('#new_task').ajaxForm({success: add_new_task, dataType: 'json', clearForm: true});
    $('.single_task_wrapper input[type="checkbox"]').live('click', switch_task_status);
    $('.single_task_wrapper .star').live('click', star_task);
    $('li.task_list a').click(function(){
      var loaded_list = $(this).attr('id');
      jQuery.get($(this).attr('js-href'), function(data, text_status){
        //$('#task_items').html('');
        $('#task_items').html(data);
        $.cookie('loaded_task_list_<%= @project.id unless @project.blank? %>', loaded_list);
      });
      return false;
    });
    var list_to_load = $.cookie('loaded_task_list_<%= @project.id unless @project.blank? %>');
    if(list_to_load){
      $('#'+list_to_load).click();
    }
    
  });
</script>
<% end %>


<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to t(".all_tasks", :default => "All tasks"), tasks_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_task_path(:project_id=>@project.to_param) %></li>
    </ul>
  </div>          
  <div class="content">        
    <%= render :partial=>"form"%>  
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Tasks</h2>
    <div class="inner">
      <ul class="task_items" id="task_items">
        <%= render :partial=>"list" %>
      </ul>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'index_sidebar') -%>

app/views/tasks/list.erb
<%= render :partial=>"list" %>

app/views/tasks/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", tasks_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_task_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Task</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/tasks/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", tasks_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_task_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", task_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.task.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @task.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.task.project_id", :default => t("activerecord.labels.project_id", :default => "Project")) %>:</b>
          <%= @task.project_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.task.user_id", :default => t("activerecord.labels.user_id", :default => "User")) %>:</b>
          <%= @task.user_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.task.is_starred", :default => t("activerecord.labels.is_starred", :default => "Is starred")) %>:</b>
          <%= @task.is_starred %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_task_path(@task), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), task_path(@task), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>