config/routes.rb
Doless::Application.routes.draw do
  
  get "profile/:id", :as=>'profile', :to=>'profile#show'

  resources :updates

  resources :tasks do
    member do
      get 'switch_completed'
      get 'switch_starred'
    end
    collection do
      get 'starred'
      get 'completed'
    end
  end

  scope ':project_id', :as=>'project' do
    resources :documents
    
    resources :tasks do
      member do
        get 'switch_completed'
      end
    end
    
    resources :tickets do
      resources :ticket_comments, :only=>[:index, :create, :destroy]
    end
    resources :topics do
      resources :posts, :only=>[:index, :create, :destroy]
    end
    resources :work_reports
  end
  resources :projects do
    collection do
      get 'all'
    end
  end
  
  resource :dashboard

  devise_for :users

  root :to => "dashboards#show"

  match ':id' => "projects#show", :as=>:short_project
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_friendly_id :title, :use_slug => true
  belongs_to :user
  belongs_to :project

  has_many :assets, :as=>"attachable"
  has_many :posts

  has_and_belongs_to_many :users


  accepts_nested_attributes_for :assets, :allow_destroy => true, :reject_if => proc { |a| a['asset'].blank? }
  accepts_nested_attributes_for :posts

  validates :title, :presence=>true
  validates :user_id, :presence=>true

  validates_associated :assets
  validates_associated :posts

  attr_accessible :title, :assets_attributes, :posts_attributes, :user_ids

  before_save :attach_user_to_assets

  def attach_user_to_assets
    self.assets.each do |a|
      a.user_id = self.user_id if a.new_record?
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_project, :only=>[:index, :show, :new, :create]
  before_filter :find_project_for_management, :only=>[:edit, :update, :destroy]
  # GET /topics
  # GET /topics.xml
  def index
    @topics = @project.topics.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = @project.topics.find(params[:id])
    # TODO: fix this
    #return(redirect_to(project_topics_url(@project))) if not @project.leaders.member?(current_user) or not @topic.users.member?(current_user)
    @assets = @project.assets.where(:attachable_type=>[Topic.to_s, Post.to_s]).where(:attachable_id=>([@topic.id]|@topic.posts.all.map{|p|p.id})).order('updated_at desc').all

    @post = @topic.posts.new
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = @project.topics.new
    @topic.posts.build
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = @project.topics.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(params[:topic])
    @topic.project = @project
    @topic.user = current_user
    @topic.posts.first.user = current_user
    respond_to do |format|
      if @topic.save
        format.html { redirect_to([@project, @topic], :notice => 'Topic was successfully created.') }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = @project.topics.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to([@project, @topic], :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = @project.topics.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(project_topics_url(@project)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_asset.html.erb
<li>
  <% if f.object.new_record? %>
    <%= f.file_field :asset %>
  <% else %>
    <%= f.object.asset_file_name %> <%= f.check_box :_destroy %><%= f.label :_destroy, t('.destroy_asset') %>
  <% end %>
</li>

app/views/topics/_form.html.erb
<%= form_for [@project, @topic], :html => { :class => :form } do |f| -%>

  <div class="group">
    <%= f.label :title, t("activerecord.attributes.topic.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description"><% t("web-app-theme.descriptions.topic.title", :default => "") %></span>
  </div>
  <% if f.object.new_record? %>
    <%= f.fields_for :posts do |fp| %>
      <div class="group">
        <%= fp.label :body, t("activerecord.attributes.post.body", :default => "Body"), :class => :label %>
		    <%= fp.text_area :body, :size=>"60x5", :class=>"text_area" %>
      </div>
    <% end %>
  <% end %>
        
  <div class="group navform wat-cf">
    <button class="button" type="submit">
      <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
    </button>
    <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
    <%= link_to t("web-app-theme.cancel", :default => "Cancel"), project_topics_path(@project), :class => "text_button_padding link_button" %>
  </div>
<% end -%>

app/views/topics/_sidebar.html.erb
<div class="block">
  <h3><%= t('.observed_by', :default=>'Topic accessible by')%></h3>
  <ul class="navigation">
		<% for u in (@topic.project.users | @project.leaders) %>
    	<li><%= link_to u.full_name, '#' %></li>
		<% end %>
  </ul>
</div>

<div class="block">
  <h3><%= t('.attached_assets', :default=>'Attached assets')%></h3>
  <ul class="navigation">
		<% for a in @assets %>
			<li><%= link_to a.asset_file_name, a.asset.url%></li>
		<% end %>
  </ul>
</div>

app/views/topics/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", topics_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_project_topic_path(@project) %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_project_topic_path(@project) %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Topic</h2>
    <div class="inner">
      <%= render :partial => "form"%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/topics/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", project_topics_path(@project)  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_project_topic_path(@project) %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Topics</h2>
    <div class="inner">
      <ul class="list">
        <% for topic in @topics %>
        <li>
          <div class="left">
            Ava
          </div>
          <div class="item">
            <h4><%= link_to topic.title, project_topic_path(@project, topic) %></h4>
            <p>

            </p>
              <small>Utworzono: <%= topic.created_at %>, ostatnia post: <%= topic.posts.last.user %> (<%= topic.posts.last.created_at %>)</small>
            
          </div>
        </li>
        <% end %>
      </ul>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<%# content_for :sidebar, render(:partial => 'index_sidebar') -%>

app/views/topics/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", project_topics_path(@project) %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_project_topic_path(@project) %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Topic</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>

<%# content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/topics/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", project_topics_path(@project)  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_project_topic_path(@project) %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", project_topic_path(@project) %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      <h3><%= @topic.title %></h3>
      <ul class="list">
        <% for p in @topic.posts  %>
          <li>
            <div class="left ">
              Ava
            </div>
            <div class="item">
              <p><%= p.body %></p>
              <p><%= p.user %> (<%= p.created_at %>)</p>
            </div>
          </li>
        <% end %>
      </ul>
      <h4><%= image_tag 'icons/comment_add.png', :class=>"header_icon", :alt=>"New comment icon" %>New post</h4> 
  		<div id="post_form" style="display: block;">
  			<%= render :partial=>"/posts/form"%>
  		</div>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_project_topic_path(@project, @topic), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), project_topic_path(@project, @topic), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>

    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>