config/routes.rb
Doless::Application.routes.draw do
  
  get "profile/:id", :as=>'profile', :to=>'profile#show'

  resources :updates

  resources :tasks do
    member do
      get 'switch_completed'
      get 'switch_starred'
    end
    collection do
      get 'starred'
      get 'completed'
    end
  end

  scope ':project_id', :as=>'project' do
    resources :documents
    
    resources :tasks do
      member do
        get 'switch_completed'
      end
    end
    
    resources :tickets do
      resources :ticket_comments, :only=>[:index, :create, :destroy]
    end
    resources :topics do
      resources :posts, :only=>[:index, :create, :destroy]
    end
    resources :work_reports
  end
  resources :projects do
    collection do
      get 'all'
    end
  end
  
  resource :dashboard

  devise_for :users

  root :to => "dashboards#show"

  match ':id' => "projects#show", :as=>:short_project
end

app/models/work_report.rb
class WorkReport < ActiveRecord::Base

  scope :ordered, order('id DESC')

  belongs_to :user
  belongs_to :project
  
  validates :report, :presence=>true
end

app/controllers/work_reports_controller.rb
class WorkReportsController < ApplicationController
  before_filter :find_project  
  # GET /work_reports
  # GET /work_reports.xml
  def index
    @work_reports = @project.work_reports.ordered.all
    @work_report = @project.work_reports.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @work_reports }
    end
  end

  # GET /work_reports/1
  # GET /work_reports/1.xml
  def show
    @work_report = @project.work_reports.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @work_report }
    end
  end

  # GET /work_reports/new
  # GET /work_reports/new.xml
  def new
    @work_report = @project.work_reports.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @work_report }
    end
  end

  # POST /work_reports
  # POST /work_reports.xml
  def create
    @work_report = @project.work_reports.new(params[:work_report])
    @work_report.user = current_user
    respond_to do |format|
      if @work_report.save
        format.html { redirect_to([@project, :work_reports], :notice => 'Work report was successfully created.') }
        format.xml  { render :xml => @work_report, :status => :created, :location => @work_report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @work_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /work_reports/1
  # DELETE /work_reports/1.xml
  def destroy
    return redirect_to(project_work_reports(@project)) unless @project.leaders.member?(current_user)
    @work_report = @project.work_reports.find(params[:id])
    @work_report.destroy

    respond_to do |format|
      format.html { redirect_to(projec_work_reports_url(@project)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/work_reports_helper.rb
module WorkReportsHelper
end

app/views/work_reports/_form.html.erb
<%= form_for [@project, @work_report], :html => { :class => :form } do |f| -%>

  <div class="group">
    <%= f.label :report, t("activerecord.attributes.work_report.report", :default => "Report"), :class => :label %>
    <%= f.text_area :report, :class => 'text_area', :size=>"60x2" %>
    <span class="description"><% t("web-app-theme.descriptions.work_report.report", :default => "") %></span>
  </div>

  <div class="group navform wat-cf">
    <button class="button" type="submit">
      <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
    </button>
    <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
    <%= link_to t("web-app-theme.cancel", :default => "Cancel"), work_reports_path, :class => "text_button_padding link_button" unless f.object.new_record? %>
  </div>
<% end -%>

app/views/work_reports/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", work_reports_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_work_report_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_work_report_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> WorkReport</h2>
    <div class="inner">
      <%= render :partial => "form"%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/work_reports/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", project_work_reports_path(@project)  %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title">
      <%= t("web-app-theme.all", :default => "All")  %> WorkReports</h2>
    <div class="inner">
      <%= render :partial=>"form" %>
      <ul class="list">
        <% for wr in @work_reports %>
          <li>
            <div class="left">
              AVA
            </div>
            <div class="item">
              <p>
                <%= insert_links_to_tickets_in_text(wr.report) %>
              </p>
              <small><%= link_to wr.user, profile_path(wr.user.to_param) %> @ <%= wr.created_at %></small>
            </div>
          </li>
        <% end %>
      </ul>
     <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/work_reports/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", work_reports_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_work_report_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  WorkReport</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/work_reports/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", work_reports_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_work_report_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", work_report_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.work_report.report", :default => t("activerecord.labels.report", :default => "Report")) %>:</b>
          <%= @work_report.report %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.work_report.user_id", :default => t("activerecord.labels.user_id", :default => "User")) %>:</b>
          <%= @work_report.user_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.work_report.project_id", :default => t("activerecord.labels.project_id", :default => "Project")) %>:</b>
          <%= @work_report.project_id %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_work_report_path(@work_report), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), work_report_path(@work_report), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>