config/routes.rb
Doless::Application.routes.draw do
  
  get "profile/:id", :as=>'profile', :to=>'profile#show'

  resources :updates

  resources :tasks do
    member do
      get 'switch_completed'
      get 'switch_starred'
    end
    collection do
      get 'starred'
      get 'completed'
    end
  end

  scope ':project_id', :as=>'project' do
    resources :documents
    
    resources :tasks do
      member do
        get 'switch_completed'
      end
    end
    
    resources :tickets do
      resources :ticket_comments, :only=>[:index, :create, :destroy]
    end
    resources :topics do
      resources :posts, :only=>[:index, :create, :destroy]
    end
    resources :work_reports
  end
  resources :projects do
    collection do
      get 'all'
    end
  end
  
  resource :dashboard

  devise_for :users

  root :to => "dashboards#show"

  match ':id' => "projects#show", :as=>:short_project
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doless</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", "style", :cache => false %>
  <%= javascript_include_tag 'jquery/jquery.min', 'jquery/jquery.cookie', 'jquery/jquery.form', 'rails', 'application', :cache => true %>
  <%= csrf_meta_tag %>
	<%= yield(:head) || "" %>
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function(){
			
			<%= yield(:body_onload) || "" %>
		});
	</script>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><%= link_to 'Doless', root_path %></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><%= link_to t("web-app-theme.profile", :default => "Profile"), edit_user_registration_path %></li>
          <li><%= link_to t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path, :class=>"logout" %></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
        	<li class="<%= controller.controller_path == 'dashboards' ? 'active' : '' %>"><%= link_to t('doless.modules.dashboard', :default=>'Dashboard'), dashboard_path %></li>
        	<li class="<%= controller.controller_path == 'updates' ? 'active' : '' %>"><%= link_to t('doless.modules.updates', :default=>'Updates'), updates_path %></li>
          <li class="<%= controller.controller_path == 'tasks' ? 'active' : '' %>"><%= link_to t('doless.modules.tasks', :default=>'Tasks'), tasks_path(:project_id=>@project)%></li>
					<% if not @project.blank? and not @project.id.blank? %>
						<li class="<%= controller.controller_path == 'projects' ? 'active' : '' %>"><%= link_to @project.name, @project %></li>
						<li class="<%= controller.controller_path == 'tickets' ? 'active' : '' %>"><%= link_to t('doless.modules.tickets', :default=>'Tickets'), project_tickets_path(@project) %></li>
            <li class="<%= controller.controller_path == 'work_reports' ? 'active' : '' %>"><%= link_to t('doless.modules.work_reports', :default=>'Work reports'), project_work_reports_path(@project) %></li>
            <li class="<%= controller.controller_path == 'documents' ? 'active' : '' %>"><%= link_to t('doless.modules.documents', :default=>'Documents'), project_documents_path(@project) %></li>
            <li class="<%= controller.controller_path == 'topics' ? 'active' : '' %>"><%= link_to t('doless.modules.forum', :default=>'Forum'), project_topics_path(@project) %></li>
					<% end %>
        </ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> <a href="http://groovyru.by">GroovyRuby</a>.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>            
    </div>
  </div>
</body>
</html>